name: Reuseable Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the artifact
        required: false
        type: string
        default: dist
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get artifacts
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.artifact-name }}
      - name: Output information
        run: echo "Deploying..."
